# Generated by Django 4.2.7 on 2023-11-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noProduto", models.CharField(max_length=200)),
                ("valorProduto", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantidadeProduto", models.IntegerField(default=0)),
            ],
        ),
    ]
