# Generated by Django 4.2.7 on 2023-11-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_rename_noproduto_produtos_nomeproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="imagem",
            field=models.CharField(default="", max_length=200),
        ),
    ]
