# Generated by Django 4.2.7 on 2023-11-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_produtos_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtdCompra", models.IntegerField(default=0)),
                ("endereco", models.CharField(default="", max_length=200)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.produtos"
                    ),
                ),
            ],
        ),
    ]
